### ISSUE TITLE
You state "Its not fast", but it can be

### ISSUE THREAD

**Issue by robertleeplummerjr** [carlosascari/lstm#1]
You stated:

>Its not fast, it was intented to look like the original to make it easer to consume if you are coming from python world.

But if you were to suggest to the libraries you depend on that they could upgrade to use something like [gpu.js](https://gpu.rocks), they could easily be many orders of magnitude faster.

This seems like it may be a difficult task, but if you see your invested work as making this project something that isn't just for understanding, but also for using it seriously, you may well help a whole host of people who'd like to simply use javascript for machine learning, because they already know it.

**Comment by carlosascari** [comment]
![robertleeplummerjr](https://user-images.githubusercontent.com/2263170/61991424-81344900-b015-11e9-88de-79b7a62c1abd.png)

:v LOL

I just recently digested the code, honestly I feel like it is quite simple to implement a LSTM once you get the main concepts behind it, however, currently all tutorials out there are not easy to digest if you were not taught linear algebra; it takes a while to wrap your head around what is going on.

Personally, I would much rather make this information easier to consume for developers who are not math savvy or do not want to be bothered with all the details.

I am pretty confident I can simplify this information so that you or anyone else can fully understand how to implement a LSTM in any language, in one afternoon.

*gpu.js* Looks very promising, whenever I find the time I will try it out, I can't promote something I have never used before in good heart. However, you are welcomed to make a PR for the readme suggesting your library. Be warned, if you do, I will be forced to put your bitcoins where you keyboard is and test your library against my vanilla js bit twiddling jujitsu hyyaaaah!

"Its not fast", I suppose you perceived that I meant it is slow in general because it is running in JS, however I actually meant it is slow since I am a optimization OCD nerd and I know that it does a lot of js-optimization no-nos (I cringe at the sight of for-in loops, makes me feel... dirty), however this code really was only intended as learning material and I chose specifically to make it visually similar to the original python code.

"...but if you see your invested work as making this project something that isn't just for understanding..., you may well help a whole host of people..."
Why you doing this to me bro, your guilt-tripping bro, cmon Bro, why you doing this! Now I have to do my part to make this world a better place :3 lol. I will update this project soon and make it simpler to digest this info, if I cannot convince you to implement a LSTM yourself then I have failed as your sempai, and will disgracefully accept your idea pitch slash self promotion.

**Comment by robertleeplummerjr** [comment]
>if I cannot convince you to implement a LSTM yourself then I have failed as your sempai

But I have already implemented a LSTM using brain.js long before ever reading your code, and in-fact a whole library that is nearly finished.  If I wanted self promotion, I would have picked a larger audience than a project with less than a handful of stars.  I can assure you I simply want as many people excited about really fast math and machine learning in JavaScript as possible.

Please don't feel disgraced, or nagative, I just want positive energy and collaboration.  It may have been better for me to simply say: "good job".  Ty again for looking into this and the thoughtful, light-hearted reaponse.

**Comment by carlosascari** [comment]
No hard feelings, it's a Kafka's Castle moment (we bind different emotions to the same words we use). I was never offended and what you saw there was a failed attempt at sarcasm lol. Cheers!

**Comment by robertleeplummerjr** [comment]
Ty ty.
